language: erlang

# Default is 16.04 (xenial) but 18.04 is needed to get TLS 1.3 working
dist: bionic

otp_release:
  - 23.0
  - 22.3
  - 22.1

notifications:
  email: false

install:
  - wget -c https://github.com/erlang/rebar3/releases/download/3.13.1/rebar3 && chmod +x rebar3
  - git clone https://github.com/inaka/elvis.git && cd elvis && rebar3 escriptize && sudo cp _build/default/bin/elvis /usr/bin && cd ..
  - eval "$(gimme 1.14)"

script:
  - go version
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
  - make ct-h2specd
