name: Ubuntu

on:
  push:
    branches: [ master,  tmp_build_tests]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go: [ '1.15', '1.14' ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.0
      with:
        otp-version: 22.0.7
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests 1
      run: make ct-h2specd
    - name: Run tests 2
      run: make ct-h2specd
    - name: Run tests 3
      run: make ct-h2specd
    - name: Run tests 4
      run: make ct-h2specd
    - name: Run tests 5
      run: make ct-h2specd
    - name: Run tests 6
      run: make ct-h2specd
    - name: Run tests 7
      run: make ct-h2specd
    - name: Run tests 8
      run: make ct-h2specd
    - name: Run tests 9
      run: make ct-h2specd
    - name: Run tests 10
      run: make ct-h2specd
    - name: Run tests 11
      run: make ct-h2specd
    - name: Run tests 12
      run: make ct-h2specd
    - name: Run tests 13
      run: make ct-h2specd
    - name: Run tests 14
      run: make ct-h2specd
    - name: Run tests 15
      run: make ct-h2specd
    - name: Run tests 16
      run: make ct-h2specd
    - name: Run tests 17
      run: make ct-h2specd
    - name: Run tests 18
      run: make ct-h2specd
    - name: Run tests 19
      run: make ct-h2specd
    - name: Run tests 20
      run: make ct-h2specd
    - name: Run tests 21
      run: make ct-h2specd
    - name: Run tests 22
      run: make ct-h2specd
    - name: Run tests 23
      run: make ct-h2specd
    - name: Run tests 24
      run: make ct-h2specd
    - name: Run tests 25
      run: make ct-h2specd
    - name: Run tests 26
      run: make ct-h2specd
    - name: Run tests 27
      run: make ct-h2specd
    - name: Run tests 28
      run: make ct-h2specd
    - name: Run tests 29
      run: make ct-h2specd
    - name: Run tests 30
      run: make ct-h2specd
    - name: Run tests 31
      run: make ct-h2specd
    - name: Run tests 32
      run: make ct-h2specd
    - name: Run tests 33
      run: make ct-h2specd
    - name: Run tests 34
      run: make ct-h2specd
    - name: Run tests 35
      run: make ct-h2specd
    - name: Run tests 36
      run: make ct-h2specd
    - name: Run tests 37
      run: make ct-h2specd
    - name: Run tests 38
      run: make ct-h2specd
    - name: Run tests 39
      run: make ct-h2specd
    - name: Run tests 40
      run: make ct-h2specd
    - name: Run tests 41
      run: make ct-h2specd
    - name: Run tests 42
      run: make ct-h2specd
    - name: Run tests 43
      run: make ct-h2specd
    - name: Run tests 44
      run: make ct-h2specd
    - name: Run tests 45
      run: make ct-h2specd
    - name: Run tests 46
      run: make ct-h2specd
    - name: Run tests 47
      run: make ct-h2specd
    - name: Run tests 48
      run: make ct-h2specd
    - name: Run tests 49
      run: make ct-h2specd
    - name: Run tests 50
      run: make ct-h2specd
