name: 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13', '1.12', '1.11', '1.10' ]

    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.0
      with:
        otp-version: 22.1  
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}  
    - name: Run tests
      run: make tests
