name:

on:
  push:
    branches: [ master,  tmp_build_tests]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14' ]

    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.0
      with:
        otp-version: 22.0.7
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Install dep
      run: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - name: Run tests 1
      run: make tests
    - name: Run tests 2
      run: make tests
    - name: Run tests 3
      run: make tests
    - name: Run tests 4
      run: make tests
    - name: Run tests 5
      run: make tests
    - name: Run tests 6
      run: make tests
    - name: Run tests 7
      run: make tests
    - name: Run tests 8
      run: make tests
    - name: Run tests 9
      run: make tests
    - name: Run tests 10
      run: make tests
